import { existsSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";
import chalk from "chalk";
import { loadConfig, DEFAULT_CONFIG } from "../lib/config.js";
import type { Provider } from "../lib/config.js";
import { ContextStore } from "../lib/context-store.js";

const CLAUDE_MD_BLOCK = `
## Repository Memory (repomemory)

This repo uses [repomemory](https://github.com/DanielGuru/repomemory) for persistent AI memory.

**At the start of every task:**
1. Use \`context_search\` to find relevant architecture, decisions, and known issues
2. Read \`.context/index.md\` for quick project orientation

**During your session:**
- Use \`context_write\` to record discoveries, decisions, and gotchas
- Use \`context_delete\` to remove stale or incorrect knowledge

**Before modifying code:**
- Search \`context_search("component name")\` for known regressions
- Check \`context_search("why")\` for past decisions before proposing alternatives

**At end of session:**
- Write a brief session summary: \`context_write(category="sessions", ...)\`
`;

export async function initCommand(options: { dir?: string; provider?: string }) {
  const repoRoot = options.dir || process.cwd();
  const config = loadConfig(repoRoot);

  if (options.provider) {
    config.provider = options.provider as Provider;
  }

  const store = new ContextStore(repoRoot, config);

  if (store.exists()) {
    console.log(chalk.yellow("\u26a0  .context/ directory already exists."));
    console.log(chalk.dim("  Run `repomemory analyze` to regenerate content."));
    return;
  }

  // Scaffold directories
  store.scaffold();

  // Write starter index
  store.writeIndex(`# Project Context

> Auto-generated by [repomemory](https://github.com/DanielGuru/repomemory). Run \`repomemory analyze\` to populate.

## Quick Orient
*Run \`repomemory analyze\` to generate project-specific orientation.*

## Context Files
- \`facts/\` \u2014 Architecture, patterns, integrations
- \`decisions/\` \u2014 Why things are this way (prevents re-debating)
- \`regressions/\` \u2014 Known gotchas, things that broke before
- \`sessions/\` \u2014 Compressed session summaries
- \`changelog/\` \u2014 Recent changes by month

## For AI Agents
Search this directory for task-relevant context before starting work.
Write new learnings using the \`context_write\` MCP tool during your session.
`);

  // Write config file from shared defaults (not a duplicate)
  const configPath = join(repoRoot, ".repomemory.json");
  if (!existsSync(configPath)) {
    const configToWrite = {
      provider: config.provider,
      model: config.model,
      contextDir: DEFAULT_CONFIG.contextDir,
      maxFilesForAnalysis: DEFAULT_CONFIG.maxFilesForAnalysis,
      maxGitCommits: DEFAULT_CONFIG.maxGitCommits,
      autoIndex: DEFAULT_CONFIG.autoIndex,
      ignorePatterns: [] as string[],
      keyFilePatterns: [] as string[],
    };
    writeFileSync(configPath, JSON.stringify(configToWrite, null, 2) + "\n");
  }

  // Add agent instructions to CLAUDE.md
  const claudeMdPath = join(repoRoot, "CLAUDE.md");
  if (existsSync(claudeMdPath)) {
    const existing = readFileSync(claudeMdPath, "utf-8");
    if (!existing.includes("repomemory")) {
      writeFileSync(claudeMdPath, existing + "\n" + CLAUDE_MD_BLOCK);
      console.log(chalk.green("\u2713 Added repomemory instructions to existing CLAUDE.md"));
    }
  } else {
    writeFileSync(claudeMdPath, `# Agent Instructions\n${CLAUDE_MD_BLOCK}`);
    console.log(chalk.green("\u2713 Created CLAUDE.md with repomemory instructions"));
  }

  console.log(chalk.green("\u2713 Initialized .context/ directory"));
  console.log();
  console.log(chalk.bold("Created:"));
  console.log(`  ${chalk.cyan(".context/index.md")}         \u2014 Quick orientation`);
  console.log(`  ${chalk.cyan(".context/facts/")}            \u2014 Architecture & patterns`);
  console.log(`  ${chalk.cyan(".context/decisions/")}        \u2014 Why things are this way`);
  console.log(`  ${chalk.cyan(".context/regressions/")}      \u2014 Known gotchas`);
  console.log(`  ${chalk.cyan(".context/sessions/")}         \u2014 Session summaries`);
  console.log(`  ${chalk.cyan(".context/changelog/")}        \u2014 Monthly changelogs`);
  console.log(`  ${chalk.cyan(".repomemory.json")}         \u2014 Configuration`);
  console.log();
  console.log(chalk.bold("Next steps:"));
  console.log();
  console.log(`  1. Set your API key:`);
  console.log(chalk.dim(`     export ANTHROPIC_API_KEY=sk-ant-...`));
  console.log(chalk.dim(`     # or: export OPENAI_API_KEY=sk-...`));
  console.log(chalk.dim(`     # or: export GEMINI_API_KEY=...`));
  console.log(chalk.dim(`     # or: export GROK_API_KEY=...`));
  console.log();
  console.log(`  2. Analyze your repo (AI-powered):`);
  console.log(chalk.dim(`     repomemory analyze`));
  console.log();
  console.log(`  3. Add the MCP server to your AI tool:`);
  console.log(chalk.dim(`     repomemory setup claude     # Claude Code`));
  console.log(chalk.dim(`     repomemory setup cursor     # Cursor`));
  console.log(chalk.dim(`     repomemory setup copilot    # GitHub Copilot`));
  console.log(chalk.dim(`     repomemory setup windsurf   # Windsurf`));
  console.log(chalk.dim(`     repomemory setup cline      # Cline`));
  console.log();
  console.log(`  4. Commit .context/ to git \u2014 your team shares the knowledge.`);
}
