import { existsSync, writeFileSync } from "fs";
import { join } from "path";
import chalk from "chalk";
import { loadConfig } from "../lib/config.js";
import { ContextStore } from "../lib/context-store.js";

const DEFAULT_REPO_CONTEXT_CONFIG = {
  provider: "anthropic",
  model: "claude-sonnet-4-5-20250929",
  ignorePatterns: [],
  keyFilePatterns: [],
  maxFilesForAnalysis: 80,
  maxGitCommits: 100,
  autoIndex: true,
  contextDir: ".context",
};

export async function initCommand(options: { dir?: string; provider?: string }) {
  const repoRoot = options.dir || process.cwd();
  const config = loadConfig(repoRoot);

  if (options.provider) {
    config.provider = options.provider as typeof config.provider;
  }

  const store = new ContextStore(repoRoot, config);

  if (store.exists()) {
    console.log(chalk.yellow("⚠  .context/ directory already exists."));
    console.log(chalk.dim("  Run `repo-context analyze` to regenerate content."));
    return;
  }

  // Scaffold directories
  store.scaffold();

  // Write starter index
  store.writeIndex(`# Project Context

> Auto-generated by [repo-context](https://github.com/repo-context/repo-context). Run \`repo-context analyze\` to populate.

## Quick Orient
*Run \`repo-context analyze\` to generate project-specific orientation.*

## Context Files
- \`facts/\` — Architecture, patterns, integrations
- \`decisions/\` — Why things are this way (prevents re-debating)
- \`regressions/\` — Known gotchas, things that broke before
- \`sessions/\` — Compressed session summaries
- \`changelog/\` — Recent changes by month

## For AI Agents
Search this directory for task-relevant context before starting work.
Write new learnings using the \`context_write\` MCP tool during your session.
`);

  // Write config file if it doesn't exist
  const configPath = join(repoRoot, ".repo-context.json");
  if (!existsSync(configPath)) {
    const configToWrite = { ...DEFAULT_REPO_CONTEXT_CONFIG };
    if (options.provider) {
      configToWrite.provider = options.provider;
    }
    writeFileSync(configPath, JSON.stringify(configToWrite, null, 2) + "\n");
  }

  console.log(chalk.green("✓ Initialized .context/ directory"));
  console.log();
  console.log(chalk.bold("Created:"));
  console.log(`  ${chalk.cyan(".context/index.md")}         — Quick orientation`);
  console.log(`  ${chalk.cyan(".context/facts/")}            — Architecture & patterns`);
  console.log(`  ${chalk.cyan(".context/decisions/")}        — Why things are this way`);
  console.log(`  ${chalk.cyan(".context/regressions/")}      — Known gotchas`);
  console.log(`  ${chalk.cyan(".context/sessions/")}         — Session summaries`);
  console.log(`  ${chalk.cyan(".context/changelog/")}        — Monthly changelogs`);
  console.log(`  ${chalk.cyan(".repo-context.json")}         — Configuration`);
  console.log();
  console.log(chalk.bold("Next steps:"));
  console.log();
  console.log(`  1. Set your API key:`);
  console.log(chalk.dim(`     export ANTHROPIC_API_KEY=sk-ant-...`));
  console.log(chalk.dim(`     # or: export OPENAI_API_KEY=sk-...`));
  console.log(chalk.dim(`     # or: export GEMINI_API_KEY=...`));
  console.log(chalk.dim(`     # or: export GROK_API_KEY=...`));
  console.log();
  console.log(`  2. Analyze your repo (AI-powered):`);
  console.log(chalk.dim(`     repo-context analyze`));
  console.log();
  console.log(`  3. Add the MCP server to your AI tool:`);
  console.log(chalk.dim(`     repo-context setup claude   # Configure Claude Code`));
  console.log(chalk.dim(`     repo-context setup cursor   # Configure Cursor`));
  console.log();
  console.log(`  4. Commit .context/ to git — your team shares the knowledge.`);
}
